name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: configure Hugo and Pagefind version
      run: |
        set -x &&
        echo "HUGO_VERSION=$(sed -n 's/^ *hugo_version: *//p' <hugo.yml)" >>$GITHUB_ENV
        echo "PAGEFIND_VERSION=$(sed -n 's/^ *pagefind_version: *//p' <hugo.yml)" >>$GITHUB_ENV

    - name: install Hugo ${{ env.HUGO_VERSION }}
      run: |
        set -x &&
        curl -Lo /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_${HUGO_VERSION}_linux-amd64.deb &&
        sudo dpkg -i /tmp/hugo.deb

    - name: run Hugo to build the pages
      run: hugo

    - name: run Pagefind ${{ env.PAGEFIND_VERSION }} to build the search index
      run: npx -y pagefind@${{ env.PAGEFIND_VERSION }} --site public

    - name: build tar archive
      run: cd public && tar czvf ../pages.tar.gz *

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: pages
        path: pages.tar.gz
